global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    target_groups:
      - targets:
          - 'localhost:9090'

  - job_name: 'web-node'
    target_groups:
      - targets:
          - '192.168.56.10:9100'

  - job_name: 'monitoring-node'
    target_groups:
      - targets:
          - 'localhost:9100'